# Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# URL de conexión (Atento a 'trustServerCertificate=true')
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=DGTOpendata;encrypt=true;trustServerCertificate=true;

# Usuario y Pass (Las que definimos en el script SQL y Docker)
spring.datasource.username=devuser
spring.datasource.password=devpassword

# Dialecto de Hibernate para SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Opcional: Para que Hibernate actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true